### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by RinatValiullov** [nikolaysalinder/loopLAB#1]
Why not Bootstrap v.5?

**Comment by nikolaysalinder** [comment]
Because v.5 beta

**Comment by RinatValiullov** [comment]
> Because v.5 beta

Is your project so responsible and important that you shouldn't use the beta version of the framework in it? And why do you want to pull jQuery into it?

**Comment by nikolaysalinder** [comment]
I'm working on the project with version 4.
